[package]
name = "cpe"
version = "0.1.0"
authors = ["Ken Johnson <ken.johnso93@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
language-tags = "0.2"
percent-encoding = "2.1"
derive_builder = "0.9"
regex = "1.4"
lazy_static = "1.4"

[features]
default = ["display"]
display = []