name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: rustfmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt -- --check
  check:
    name: check and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - 1.65.0 # MSRV

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy -- -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
